#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
  export API_KEY=45239802
  export API_SECRET=1019c9469125d71b94a79f61d888a3beb652ba5b
fi

if [ -d "cache" ]
then
  rm -rf cache/
fi

php -S localhost:8080 -t web web/index.php
